### ISSUE TITLE
can you give me a copy of SFA Net?

### ISSUE THREAD

**Issue by yjsb** [pvh1602/GCUnet-PolypSeg#1]
the code seem to deleted by the author.

**Comment by pvh1602** [comment]
I'm sorry, what does SFA mean?

**Comment by yjsb** [comment]
It's the code of 'Selective Feature Aggregation Network with Area-Boundary Constraints for Polyp Segmentation', MICCAI 2019, I try to use the official link but it seems to be deleted.

**Comment by pvh1602** [comment]
Oh sorry, my implementation does not include that SFA module.  Maybe you should email the authors for the implementation.

**Comment by yjsb** [comment]
OK，thanks
